[package]
name = "ballot"
version = "0.1.0"
authors = []
edition = "2018"

[dependencies]
map_vec = "0.2"
oasis-std = "0.2"
serde = { version = "1.0", features = ["derive"] }

[dev-dependencies]
oasis-test = "0.2"

[profile.release]
lto = true
opt-level = "z"
panic = "abort"
